version: '3.8' # you can remove version
name: expense
networks:  # top level, it is accessible throughout
  default:
    name: expense # checks if network is present or not if not creates it
volumes:
  mysql: # docker volume create mysql
    external: true # docker volume create expense
services:
  mysql:
    image: mysql:v1.0.0
    container_name: mysql # equlal to --name mysql 
    volumes:
    - source: mysql # -v volume-name:/path-in-container
      target: /var/lib/mysql
      type: volume
  backend:
    image: backend:v1.0.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js" # wait 20 seconds for mysql to complete
    depends_on:
    - mysql
  frontend:
    image: frontend:v1.0.0
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"
    
    
